"""First

Revision ID: 23a721a406f7
Revises: 
Create Date: 2021-10-22 15:58:43.465522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a721a406f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('make', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('miles', sa.String(length=7), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('horsepower', sa.String(length=5), nullable=True),
    sa.Column('torque', sa.String(length=5), nullable=True),
    sa.Column('modifications', sa.String(length=300), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('user')
    # ### end Alembic commands ###
